/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8p2_felixdominguez_12141043;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo I7
 */
public class Principal extends javax.swing.JFrame {
    Color a;
    DefaultComboBoxModel modelo;
    ArrayList<Auto>autos=new ArrayList();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        AdminAuto aa=new AdminAuto("./Autos.cbm");
        aa.cargarArchivo();
        modelo=new DefaultComboBoxModel(aa.getLista().toArray());
        ComboBoxAgregar.setModel(modelo);
        autos=aa.getLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComenzarBoton = new javax.swing.JButton();
        PRBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        PistaTexto = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LargoTexto = new javax.swing.JLabel();
        Progreso = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        ComboBoxAgregar = new javax.swing.JComboBox<>();
        AgregarBoton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        PistaNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PistaLargo = new javax.swing.JTextField();
        PistaUsarBoton = new javax.swing.JButton();
        ReiniciarBoton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        NumeroID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CorredorNombre = new javax.swing.JTextField();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        ColorBoton = new javax.swing.JButton();
        GuardarBoton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComenzarBoton.setText("Comenzar");
        ComenzarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComenzarBotonActionPerformed(evt);
            }
        });

        PRBoton.setText("Pausar");
        PRBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PRBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Pista:");

        PistaTexto.setText("______");

        jLabel3.setText("Largo:");

        LargoTexto.setText("______");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Corredor", "Distancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);

        AgregarBoton.setText("Agregar");
        AgregarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarBotonActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de la Pista:");

        PistaNombre.setText(" ");

        jLabel4.setText("Largo de la Pista:");

        PistaLargo.setText(" ");

        PistaUsarBoton.setText("Usar Pista");
        PistaUsarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PistaUsarBotonActionPerformed(evt);
            }
        });

        ReiniciarBoton.setText("Reiniciar");
        ReiniciarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReiniciarBotonActionPerformed(evt);
            }
        });

        jLabel5.setText("Numero Identificador:");

        jLabel6.setText("Nombre del Corredor:");

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "McQueen", "Convertible", "Nascar" }));

        ColorBoton.setText("Color");
        ColorBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorBotonActionPerformed(evt);
            }
        });

        GuardarBoton.setText("Guardar");
        GuardarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarBotonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComenzarBoton)
                        .addGap(18, 18, 18)
                        .addComponent(PRBoton)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PistaTexto)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LargoTexto))
                    .addComponent(Progreso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AgregarBoton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GuardarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(NumeroID)
                                    .addComponent(CorredorNombre)
                                    .addComponent(ColorBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PistaLargo)
                            .addComponent(PistaNombre)
                            .addComponent(PistaUsarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ReiniciarBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComenzarBoton)
                    .addComponent(PRBoton)
                    .addComponent(jLabel1)
                    .addComponent(PistaTexto)
                    .addComponent(jLabel3)
                    .addComponent(LargoTexto))
                .addGap(18, 18, 18)
                .addComponent(Progreso, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarBoton)
                    .addComponent(jLabel2)
                    .addComponent(PistaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(PistaLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(NumeroID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PistaUsarBoton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(CorredorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReiniciarBoton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ColorBoton)))
                .addGap(18, 18, 18)
                .addComponent(GuardarBoton)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComenzarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComenzarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComenzarBotonActionPerformed

    private void PRBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PRBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PRBotonActionPerformed

    private void AgregarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarBotonActionPerformed
        // TODO add your handling code here:
        /*Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificador", "Corredor", "Distancia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla);*/
        
        Object[] fila={
                autos.get(ComboBoxAgregar.getSelectedIndex()).getId(),
                autos.get(ComboBoxAgregar.getSelectedIndex()).getNombre(),
                autos.get(ComboBoxAgregar.getSelectedIndex()).getDistancia()
            };
            DefaultTableModel model = (DefaultTableModel) Tabla.getModel();
            model.addRow(fila);
            Tabla.setModel(model);
        
    }//GEN-LAST:event_AgregarBotonActionPerformed

    private void ColorBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorBotonActionPerformed
        // TODO add your handling code here:
        a=JColorChooser.showDialog(rootPane, "Elige el Color del Auto", Color.yellow);
        ColorBoton.setBackground(a);
    }//GEN-LAST:event_ColorBotonActionPerformed

    private void GuardarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarBotonActionPerformed
        // TODO add your handling code here:
        try{
            String i=NumeroID.getText().replace(" ", "");
            int id=Integer.parseInt(i);
            if(unico(id)==true){
                JOptionPane.showMessageDialog(null, "Debe de ingresar un numero identificador que no exista aun");
                
            }else{
                if(ComboBoxTipo.getSelectedItem()=="McQueen"){
                    McQueen m=new McQueen(id,CorredorNombre.getText(),a);
                    modelo.addElement(m);
                    ComboBoxAgregar.setModel(modelo);
                    AdminAuto aa=new AdminAuto("./Autos.cbm");
                    aa.cargarArchivo();
                    aa.setPersona(m);
                    aa.escribirArchivo();
                    JOptionPane.showMessageDialog(null, "Se ha agregado excitosamente");
                    autos.add(m);
                }else if(ComboBoxTipo.getSelectedItem()=="Convertible"){
                    Convertible m=new Convertible(id,CorredorNombre.getText(),a);
                    modelo.addElement(m);
                    ComboBoxAgregar.setModel(modelo);
                    AdminAuto aa=new AdminAuto("./Autos.cbm");
                    aa.cargarArchivo();
                    aa.setPersona(m);
                    aa.escribirArchivo();
                    JOptionPane.showMessageDialog(null, "Se ha agregado excitosamente");
                    autos.add(m);
                }else if(ComboBoxTipo.getSelectedItem()=="Nacar"){
                    Nascar m=new Nascar(id,CorredorNombre.getText(),a);
                    modelo.addElement(m);
                    ComboBoxAgregar.setModel(modelo);
                    AdminAuto aa=new AdminAuto("./Autos.cbm");
                    aa.cargarArchivo();
                    aa.setPersona(m);
                    aa.escribirArchivo();
                    JOptionPane.showMessageDialog(null, "Se ha agregado excitosamente");
                    autos.add(m);
                }
            }    
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Ingrese los datos correctos");
        }    
    }//GEN-LAST:event_GuardarBotonActionPerformed

    private void PistaUsarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PistaUsarBotonActionPerformed
        // TODO add your handling code here:
        PistaTexto.setText(PistaNombre.getText());
        LargoTexto.setText(PistaLargo.getText());
    }//GEN-LAST:event_PistaUsarBotonActionPerformed

    private void ReiniciarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReiniciarBotonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReiniciarBotonActionPerformed

    public boolean unico(int b){
        boolean y=false;
        for(int i=0;i<autos.size();i++){
            if(b==autos.get(i).getId()){
                y=true;
            }
        }
        return y;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try{
            UIManager.setLookAndFeel(new FlatDarkLaf());
        }catch(Exception e){
            e.printStackTrace();
        }
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarBoton;
    private javax.swing.JButton ColorBoton;
    private javax.swing.JComboBox<String> ComboBoxAgregar;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JButton ComenzarBoton;
    private javax.swing.JTextField CorredorNombre;
    private javax.swing.JButton GuardarBoton;
    private javax.swing.JLabel LargoTexto;
    private javax.swing.JTextField NumeroID;
    private javax.swing.JButton PRBoton;
    private javax.swing.JTextField PistaLargo;
    private javax.swing.JTextField PistaNombre;
    private javax.swing.JLabel PistaTexto;
    private javax.swing.JButton PistaUsarBoton;
    private javax.swing.JProgressBar Progreso;
    private javax.swing.JButton ReiniciarBoton;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
